from collections import deque

pinterest_titles = deque([
    "17 Reasons Why Your Pinterest Traffic is Dropping!",
    "How to Find Pinterest Keywords & Skyrocket Your Blog Traffic! oage 15",
    "9 Pin Design Mistakes That Are Costing You Clicks and Traffic",
    "How I Created a Viral Pin That Increased My Blog Earnings",
    "How to Make Your Website Pinterest Friendly",
    "A Step-By-Step Guide To Pinterest SEO Strategies To Boost Traffic",
    "How To Schedule Your Pinterest Pins Using The Canva Content Planner",
    "The Ultimate Pinterest Traffic Strategy For Bloggers & E-Commerce Shops",
    "How To Create A Pinterest Board Strategy For Your Shop (Etsy & Shopify)",
    "Pinterest Trends: How To Use This Keyword Tool For Content Planning",
    "How To Do Affiliate Marketing On Pinterest With A Blog",
    "Pinterest Analytics: A Simple Guide To Read & Analyze Your Data",
    "4 Steps For Creating An Effective Pinterest Workflow That Produces Results",
    "How To Get Traffic To Your YouTube Channel Using Pinterest",
    "How To Schedule Idea Pins On Pinterest",
    "How To Promote Your Etsy Shop On Pinterest: Optimizing Your Account",
    "What Not Do If You Start A Pinterest Account In 2023",
    "How To Use Tailwind For Pinterest & Automate Your Pins In One Hour Per Week (OR LESS)",
    "How To Use Pinterest For Affiliate Marketing",
    "How To Increase Pinterest Engagement With This Single Tactic",
    "What Are The Different Types Of Pins On Pinterest? (+ When To Use Each)",
    "6 Things I Wish Every New Pinterest Creator Would Do",
    "How To Launch Pinterest Idea Pin Ads + Video Tutorial",
    "How To Outline Successful Idea Pins",
    "How To Batch Create Pinterest Pins For A Month Using Canva",
    "How To Create Viral Idea Pins To Stop The Scroll On Pinterest",
    "Pinterest Creator Rewards Program: Everything You Need To Know To Make Money With Idea Pins",
    "Manual Pinning Strategy Vs Scheduled Pinning Using Tailwind",
    "6 Pinterest Idea Pin Mistakes To Avoid Making",
    "5 Pillars Of A Pinterest Strategy",
    "How To Convert Canva Templates To PSD Files And PSD To Canva For Free",
    "How To Create Pins For Pinterest In Canva: A Pinterest Image Workflow To Save Time",
    "How To Write Your Pinterest Descriptions To Get More Clicks & Rank Higher",
    "How To Make Story Pins On Pinterest",
    "How To Setup Your Pinterest Ads Reporting To Know If Your Ads Are Working (Or Not)"
])